### PR TITLE
Removed per client/server mempool and moved

### PR DESCRIPTION
**Pull request by srkukarni**
to a global mempool

### CODE REVIEW

**Comment by kramasamy** [comment]
@srkukarni - is this really needed for state?

**Comment by srkukarni** [comment]
Yes. I need to make stmgr-server own the messages that it gets to send to the instances. Which necessitates these changes.
Plus the current set of pools are really bad. One has no control over how much memory is used. Using a global pool actually gives us the ability to control usage better.

**Comment by kramasamy** [comment]
ok. we need to propagate these changes incrementally though.

**Comment by srkukarni** [comment]
After I merge this change in, can you cherry pick this one into mainline?

**Pull request merged**
