### PR TITLE
pass cluster,role,env to ckptmgr

### PR DESCRIPTION
**Pull request by nlu90**

### CODE REVIEW

**Comment by maosongfu** [comment]
Take stream mgr as an example: https://github.com/srkukarni/heron/blob/master/heron/stmgr/src/cpp/server/stmgr-main.cpp#L31

I don't know why we need to pass these as arguments to main method. On the one hand, not sure whether they are needed. On the other hand, even if they are needed, they would be used only for some detailed implementation, for instance, hdfs case. Then they should be part of implementation config instead of putting them here.

**Comment by kramasamy** [comment]
@maosongfu - they are needed for storing files. now since the cluster is named based on the directory of the config, explicitly adding again into a separate config is redundant. Since all these values are already available in the heron executor, simply pass it in the command line.

**Comment by maosongfu** [comment]
@kramasamy 
"now since the cluster is named based on the directory of the config"
What you said are all storing implementation details. Please distinguish the checkpointmgr skeleton, checkpoint storing interface and checkpoint storing implementation. Providing these arguments to main method means to provide them to checkpoint mgr skeleton; but in fact, these configs are used with checkpoint storing implementation. 

Please make the design clean (though implementation can be a little dirty); otherwise it is a huge tech debt and refactoring requires huge amount of code change. For instance, current scheduler config part is in a pretty bad shape and the refactoring is super hard.

**Comment by nlu90** [comment]
this change is integrated into another PR #9

**Pull request closed without merging**
